### PR TITLE
Add Yii2 extension reference to README

### PR DESCRIPTION
**Pull request by saada**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Give me some time to think about this. :)

**Comment by GrahamCampbell** [comment]
I've decided that I don't want to encourage people to have an automated loading system given that it's so quick and easy for people to write one for themselves.

**Comment by saada** [comment]
@GrahamCampbell , I see that you added CakePHP integration reference on the Readme. Can we reopen this pull-request then?

**Comment by GrahamCampbell** [comment]
Meh, added it. I might remove them both though. Not decided yet.

**Comment by GrahamCampbell** [comment]
I don't think an integration is needed, that's all.

**Comment by saada** [comment]
The reason why it's needed in Yii2 is because of error handling. Errors happening at the model instantiation/creation/update/delete are not logged by default. The integration piece takes care of these issues among other framework specific issues.

**Pull request closed without merging**
